export default {
  "0e384e19": [() => import(/* webpackChunkName: "0e384e19" */ "@site/docs/intro.md"), "@site/docs/intro.md", require.resolveWeak("@site/docs/intro.md")],
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "1d6b8369": [() => import(/* webpackChunkName: "1d6b8369" */ "@site/docs/Atoms/Button.md"), "@site/docs/Atoms/Button.md", require.resolveWeak("@site/docs/Atoms/Button.md")],
  "1df93b7f": [() => import(/* webpackChunkName: "1df93b7f" */ "@site/src/pages/index.tsx"), "@site/src/pages/index.tsx", require.resolveWeak("@site/src/pages/index.tsx")],
  "3797b3ba": [() => import(/* webpackChunkName: "3797b3ba" */ "@generated/docusaurus-plugin-content-docs/default/p/nucleus-docs-9fe.json"), "@generated/docusaurus-plugin-content-docs/default/p/nucleus-docs-9fe.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/p/nucleus-docs-9fe.json")],
  "3a54491e": [() => import(/* webpackChunkName: "3a54491e" */ "@site/docs/Hooks/useLocalStorage.md"), "@site/docs/Hooks/useLocalStorage.md", require.resolveWeak("@site/docs/Hooks/useLocalStorage.md")],
  "5d58a550": [() => import(/* webpackChunkName: "5d58a550" */ "@site/docs/Atoms/index.md"), "@site/docs/Atoms/index.md", require.resolveWeak("@site/docs/Atoms/index.md")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "5e9f5e1a": [() => import(/* webpackChunkName: "5e9f5e1a" */ "@generated/docusaurus.config"), "@generated/docusaurus.config", require.resolveWeak("@generated/docusaurus.config")],
  "883de1f5": [() => import(/* webpackChunkName: "883de1f5" */ "@site/docs/Hooks/index.md"), "@site/docs/Hooks/index.md", require.resolveWeak("@site/docs/Hooks/index.md")],
  "a7456010": [() => import(/* webpackChunkName: "a7456010" */ "@generated/docusaurus-plugin-content-pages/default/__plugin.json"), "@generated/docusaurus-plugin-content-pages/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-pages/default/__plugin.json")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "aba21aa0": [() => import(/* webpackChunkName: "aba21aa0" */ "@generated/docusaurus-plugin-content-docs/default/__plugin.json"), "@generated/docusaurus-plugin-content-docs/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/__plugin.json")],};
