name: Build and Publish Docusaurus Docs

on:
  push:
    branches:
      - docsify
      
permissions:
  contents:write  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: cd docs-site && npm install

      - name: Build Docusaurus site
        run: cd docs-site && npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./docs-site/build
